reviews:
  auto_review:
    enabled: true

  # Do NOT block merges — suggestions only
  request_changes_workflow: false

  # Useful but lightweight feedback
  high_level_summary: true
  review_status: true
  poem: false

  # Global context for all reviews
  general_instructions: |
    This is a time-bound hackathon project for AI Agents Assemble (WeMakeDevs).
    The goal is to demonstrate working ideas, integrations, and learning.
    Favor clarity, correctness, and progress over production hardening.
    Do not enforce enterprise-level security or infrastructure patterns.

  # Language-specific guidance
  path_instructions:
    - path: "**/*.js"
      instructions: |
        Focus on:
        - Code clarity and readability
        - Correct logic and basic error handling
        - Maintainable structure
        - Clear comments and intent
        Avoid suggesting enterprise-grade security, auth systems, or heavy abstractions.

    - path: "**/*.py"
      instructions: |
        Focus on:
        - Correctness of logic
        - Clear function intent and structure
        - Reasonable error handling
        Avoid enforcing production ML infrastructure patterns
        (auth, rate limiting, prompt injection defense, async queues).

    - path: "**/*.yml"
      instructions: |
        Review workflows for correctness and clarity.
        Avoid enforcing enterprise CI/CD security constraints.

language: en-US

tone_instructions: "Be concise, pragmatic, and hackathon-focused."
